version: "3.8"
services:
  main:
    build: .
    restart: unless-stopped
    container_name: discord-twitch-bot
    volumes:
      - type: bind
        source: ./data
        target: /opt/discord-twitch-bot/data
    env_file:
      - path: ./.env.production
        required: true
    environment:
      - NODE_ENV
      - DISCORD_TOKEN
      - DISCORD_CLIENTID
volumes:
  discord-twitch-bot: