version: "3.8"
services:
  main:
    build: .
    container_name: discord-twitch-bot
    volumes:
      - /home/exenifix/mybot-data:/app/data
    environment:
      - DISCORD_TOKEN
      - DISCORD_CLIENTID