version: "3.8"
services:
  main:
    build: .
    restart: unless-stopped
    container_name: discord-twitch-bot
    env_file:
      - path: ./.env.production
        required: true
    ports:
      - 8080:8080
    environment:
      - NODE_ENV
      - DISCORD_TOKEN
      - DISCORD_CLIENTID
      - TWITCH_CLIENTSECRET
      - TWITCH_CLIENTID
      - TWITCH_SESSION_SECRET
      - TWITCH_CALLBACK_URL
      - TWITCH_WEBHOOK_CALLBACK_URL
      - DATABASE_TYPE
      - DATABASE
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_PORT
    volumes:
      - discord-twitch-bot-prod:/usr/src/bot/data
volumes:
  discord-twitch-bot-prod: