version: "3.8"
services:
  main:
    build: .
    container_name: discord-twitch-bot
    volumes:
      - $HOME/mybot-data:/app/data
    env_file:
      - path: ./.env
        required: true
    environment:
      - NODE_ENV
      - DISCORD_TOKEN
      - DISCORD_CLIENTID