name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENTID: ${{ secrets.DISCORD_CLIENTID }}

      - name: Cleanup Unused Images
        run: docker image prune -f
