name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build
        env:
          NODE_ENV: production
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENTID: ${{ secrets.DISCORD_CLIENTID }}
          TWITCH_CLIENTSECRET: ${{ secrets.TWITCH_CLIENTSECRET }}
          TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENTID }}
          TWITCH_SESSION_SECRET: ${{ secrets.TWITCH_SESSION_SECRET }}
          TWITCH_CALLBACK_URL: ${{ secrets.TWITCH_CALLBACK_URL }}
          TWITCH_WEBHOOK_CALLBACK_URL: ${{ secrets.TWITCH_WEBHOOK_CALLBACK_URL }}
          DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
          DATABASE: ${{ secrets.DATABASE }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}

      - name: Cleanup Unused Images
        run: docker image prune -f
